repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: commit-msg
        args: [ '--pattern', '^(build|debug|ci|docs|feat|fix|perf|revert|refactor|style|test): .*']